<?php

namespace App\Models;

use CodeIgniter\Model;

class TreatmentModel extends Model
{

    protected $table      = 'DBAMV.TB_ATENDIME';
    protected $primaryKey = 'CD_ATENDIMENTO';
    protected $returnType = 'array';
    protected $allowedFields = [
        "CD_ATENDIMENTO",
        "CD_ORI_ATE",
        "CD_PACIENTE",
        "CD_CONVENIO",
        "CD_PRO_INT",
        "CD_PRO_INT_PROCEDIMENTO_ENTRAD",
        "DT_ATENDIMENTO",
        "HR_ATENDIMENTO",
        "TP_ATENDIMENTO",
        "CD_PRESTADOR",
        "CD_LEITO",
        "CD_LOC_TRANS",
        "CD_MOT_ALT",
        "CD_CID",
        "CD_SERVICO",
        "DS_ATENDIMENTO",
        "DT_DIAG",
        "DT_ALTA",
        "DS_OBS_ALTA",
        "DT_ENTRADA_SAME",
        "DT_PREVISTA_ALTA",
        "CD_TIP_RES",
        "CD_TIP_ACOM",
        "DT_VAL_GUIA",
        "NR_GUIA",
        "HR_ALTA",
        "CD_SER_DIS",
        "CD_DES_ATE",
        "DS_ATE_OCO",
        "CD_ULTIMO_MOV_INT",
        "CD_CASOS_ATD",
        "DS_DESTINO_TRANSFERENCIA",
        "NM_USUARIO",
        "CD_CON_PLA",
        "NM_USUARIO_ALTA",
        "CD_TIPO_INTERNACAO",
        "CD_LOG_EXPORT_ATENDIME",
        "CD_LOC_PROCED",
        "CD_LOG_EXPORT_ALTA",
        "SN_ACOMPANHANTE",
        "SN_INFECCAO",
        "SN_RETORNO",
        "CD_SSM_CIH",
        "CD_CONVENIO_SECUNDARIO",
        "CD_CON_PLA_SECUNDARIO",
        "CD_MULTI_EMPRESA",
        "CD_ESPECIALID",
        "CD_TIP_MAR",
        "DT_REVISAO",
        "DT_RETORNO",
        "CD_ATENDIMENTO_PAI",
        "QT_SESSOES",
        "DT_ALTA_MEDICA",
        "NM_USUARIO_ALTA_MEDICA",
        "HR_ALTA_MEDICA",
        "CD_SERVICO_SAIDA",
        "CD_ESPECIALID_SAIDA",
        "CD_LOC_TRANS_SAIDA",
        "CD_MOT_TRANS_SAIDA",
        "DS_OBS_PSIH",
        "DT_AVISO_MEDICO",
        "HR_AVISO_MEDICO",
        "DS_AVISO_TP_CONTATO",
        "DS_AVISO_OBS",
        "NM_AVISO_USUARIO",
        "SN_OBITO",
        "TP_PROGRAMA_ALTA_UNIDADE",
        "DS_PROGRAMA_ALTA",
        "DT_PROGRAMA_ALTA",
        "NM_USUARIO_PROG_ALTA",
        "DT_LIBERACAO",
        "SN_IMPORTA_AUTO",
        "CD_SUB_PLANO",
        "SN_BUSCA_ATIVA",
        "TP_BUSCA_ATIVA",
        "SN_EM_ATENDIMENTO",
        "CD_TIP_SITUACAO",
        "TP_PRIORIDADE",
        "CD_SSM_SIA",
        "CD_GRU_ATE",
        "SN_CONSULTA_SIASUS",
        "NM_USUARIO_RETORNO",
        "DT_USUARIO_RETORNO",
        "SN_RECEBE_VISITA",
        "CD_TIP_ACOM_COBERTURA",
        "NR_CHAMADA_PAINEL",
        "NR_LAUDO",
        "NR_LAUDO_ALTO_CUSTO",
        "CD_USUARIO_DIAG",
        "CD_USUARIO_UPD_DIAG",
        "DT_ULTIMA_UPD_DIAG",
        "NR_PEDIDO_LAUDO",
        "CD_ESCALA_DIA",
        "HR_AGENDA",
        "CD_SETOR_OBITO",
        "NR_DECLARACAO_OBITO",
        "DT_SOLIC_MEDICA",
        "NR_SEQ_PREIMPRE",
        "SN_ATENDIMENTO_APAC",
        "SN_OBITO_INFEC",
        "DT_CHEGADA_PACIENTE",
        "NR_CARTEIRA",
        "DT_VALIDADE",
        "NM_EMPRESA",
        "NR_CARTEIRA_ACOPLAMENTO",
        "DT_VALIDADE_ACOPLAMENTO",
        "NM_EMPRESA_ACOPLAMENTO",
        "SENHA_SUS",
        "HR_ATENDIMENTO_MEDICO",
        "CD_SEQ_INTEGRA",
        "DT_INTEGRA",
        "SN_PACIENTE_PAGA_DIF_DIARIA",
        "CD_GUIA",
        "CD_LAUDO_APAC",
        "TP_DOENCA",
        "NR_TEMPO_DOENCA",
        "TP_TEMPO_DOENCA",
        "TP_CARATER_INTERNACAO",
        "TP_OBITO_MULHER",
        "TP_ACIDENTE_TISS",
        "CD_ATENDIMENTO_SUS_VINCULADO",
        "TP_ATENDIMENTO_TISS",
        "SN_GESTACAO_TISS",
        "SN_ABORTO_TISS",
        "SN_TRANSTORNO_TISS",
        "SN_COMPLICACAO_TISS",
        "SN_ATEND_NEO_TISS",
        "SN_COMPLICACAO_NEO_TISS",
        "SN_BAIXO_PESO_TISS",
        "SN_CESARIO_TISS",
        "SN_RECEM_NATO",
        "SN_NOTIFICAR_POLICIA",
        "SN_CUSTODIA_POLICIAL",
        "CD_CID_OBITO",
        "SN_NORMAL_TISS",
        "NR_GUIA_ENVIO_PRINCIPAL",
        "CD_PROCEDIMENTO",
        "CD_CBO_PRESTADOR",
        "CD_CARATER_ATENDIMENTO",
        "CD_PROCEDIMENTO_ALTA",
        "SN_PAGA_ACOMPANHANTE",
        "CD_SETOR_LOCAL_FSCC",
        "SN_PACOTE",
        "SN_PACOTE_DAY_CLINIC",
        "CD_ATENDIMENTO_INTEGRA",
        "NR_TAG_ATENDIMENTO",
        "CD_PRESTADOR_EM_ATENDIMENTO",
        "SN_RELACAO_TRABALHO",
        "SN_SUSPEITA_EPIDEMIA",
        "SN_REAVALIACAO",
        "CD_RES_LEI_REGULACAO",
        "SN_INTERNADO",
        "CD_ATENDIMENTO_ORIGINAL",
        "CD_MEIO_TRANSPORTE",
        "DH_ALTA_MEDICA_LANCADA",
        "DH_ALTA_LANCADA",
        "NM_USUARIO_AUTORIZADOR"
    ];


    public function getByPatient($patientId){
        $query   = $this->db->query('SELECT * FROM DBAMV.TB_ATENDIME WHERE CD_PACIENTE = ' . $this->db->escape($patientId) . 
          ' ORDER BY CD_ATENDIMENTO DESC ');
        $results = $query->getResult();
        return $results;      
    }
}

?>        